# -*- coding: utf-8 -*-

"""
    helloworld

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

import jsonpickle
import dateutil.parser
from .controller_test_base import ControllerTestBase
from ..test_helper import TestHelper
from helloworld.api_helper import APIHelper


class HelloworldControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(HelloworldControllerTests, cls).setUpClass()
        cls.controller = cls.api_client.helloworld

    # Testcase for testing endpoint Helloworld_GET
    def test_helloworld_get_1(self):

        # Perform the API call through the SDK function
        result = self.controller.get_helloworld_get()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)
        
        # Test whether the captured response is as we expected
        self.assertIsNotNone(result)
        expected_body = APIHelper.json_deserialize('{"message":"Hello world"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.raw_body)
        self.assertTrue(TestHelper.match_body(expected_body, received_body))


