# -*- coding: utf-8 -*-

"""
    helloworld

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from helloworld.api_helper import APIHelper
from helloworld.configuration import Configuration
from helloworld.controllers.base_controller import BaseController
from helloworld.models.hello_world_response import HelloWorldResponse

class HelloworldController(BaseController):

    """A Controller to access Endpoints in the helloworld API."""


    def get_helloworld_get(self):
        """Does a GET request to /helloworld.

        TODO: type endpoint description here.

        Returns:
            HelloWorldResponse: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _url_path = '/helloworld'
        _query_builder = Configuration.get_base_uri()
        _query_builder += _url_path
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json'
        }

        # Prepare and execute request
        _request = self.http_client.get(_query_url, headers=_headers)
        _context = self.execute_request(_request)
        self.validate_response(_context)

        # Return appropriate type
        return APIHelper.json_deserialize(_context.response.raw_body, HelloWorldResponse.from_dictionary)
